name: Clarity CI
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Clarinet
        uses: hirosystems/setup-clarinet@v3
        with:
          clarinet-version: '3.11.0'
      - name: Clarinet Check
        run: |
          cd stacks-contracts
          clarinet check
