name: Clarity CI
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Clarinet
        uses: stx-labs/setup-clarinet@v1
        with:
          clarinet-version: '2.11.0'
      - name: Clarinet Check
        run: |
          cd contract
          clarinet check
